import localFont from "next/font/local";
import "./globals.css";
import { NavbarForAnon, NavbarForUser } from "./ui/navbar";
import { getSessionUser } from "./lib/sessions";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Jref.io",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const user = await getSessionUser();
  const loggedIn = user !== null;
  const Navbar = loggedIn ? <NavbarForUser /> : <NavbarForAnon />
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen px-10`}
      >
        {Navbar}
        {children}
      </body>
    </html>
  );
}
